# -*- coding: utf-8 -*-
"""Proyek Akhir : Image Classification Model Deployment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rr9ZRdRmcSdfi9oCf4o6N0U4o2hfoA_m
"""

!pip install -q kaggle

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!ls ~/.kaggle

!kaggle datasets download -d andrewmvd/animal-faces

# direktori baru
!mkdir datapict
!unzip -qq animal-faces.zip -d datapict
!ls datapict

!sudo apt install tree

# melihat susunan direktori
!tree -d datapict/

# hapus direktori
import shutil

shutil.rmtree('datapict/afhq/val')

!tree -d datapict/

!pip install split_folders tqdm

import splitfolders

splitfolders.ratio('datapict/afhq/animal/', output = 'datapict/afhq/animal/data_model', seed = 3, ratio = (0.8, 0.2))

import os

base_dir = 'datapict/afhq/animal/data_model'
train_dir = os.path.join(base_dir, 'train')
validation_dir = os.path.join(base_dir, 'val')

train_cat_dir = os.path.join(train_dir, 'cat')
train_dog_dir = os.path.join(train_dir, 'dog')
train_wild_dir = os.path.join(train_dir, 'wild')

validation_cat_dir = os.path.join(validation_dir, 'cat')
validation_dog_dir = os.path.join(validation_dir, 'dog')
validation_wild_dir = os.path.join(validation_dir, 'wild')

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import random

cat_files = os.listdir(train_cat_dir)
dog_files = os.listdir(train_dog_dir)
wild_files = os.listdir(train_wild_dir)

pic_index = random.randrange(0, 1000)

next_cat = [os.path.join(train_cat_dir, fname) 
                for fname in cat_files[pic_index-2:pic_index]]
next_dog = [os.path.join(train_dog_dir, fname) 
                for fname in dog_files[pic_index-2:pic_index]]
next_wild = [os.path.join(train_wild_dir, fname) 
                for fname in wild_files[pic_index-2:pic_index]]

for i, img_path in enumerate(next_cat + next_dog + next_wild):
  img = mpimg.imread(img_path)
  plt.imshow(img)
  plt.axis('Off')
  plt.show()

import tensorflow as tf
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale = 1./255,
                                   rotation_range = 40,
                                   width_shift_range = 0.2,
                                   height_shift_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True,
                                   shear_range = 0.2,
                                   fill_mode = 'nearest')
 
test_datagen = ImageDataGenerator(rescale = 1./255,
                                  rotation_range = 40,
                                  width_shift_range = 0.2,
                                  height_shift_range = 0.2,
                                  zoom_range = 0.2,
                                  horizontal_flip = True,
                                  shear_range = 0.2,
                                  fill_mode = 'nearest')

train_generator = train_datagen.flow_from_directory(
    train_dir,  # direktori data latih
    target_size = (150, 150),  
    batch_size = 20,
    class_mode = 'categorical')
 
validation_generator = test_datagen.flow_from_directory(
    validation_dir, # direktori data validasi
    target_size = (150, 150), 
    batch_size = 20, 
    class_mode = 'categorical')

tf.device('/device:GPU:0')

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(64, (3,3), activation = 'relu', input_shape = (150, 150, 3)),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(64, (3,3), activation = 'relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(128, (3,3), activation = 'relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(128, (3,3), activation = 'relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dropout(0.5), 
    tf.keras.layers.Dense(512, activation = 'relu'),
    tf.keras.layers.Dense(3, activation = 'softmax')
])

model.compile(optimizer = 'adam',
              loss = 'categorical_crossentropy',
              metrics = ['accuracy']
              )

class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs = {}):
    if(logs.get('accuracy') > 0.90 and logs.get('val_accuracy') > 0.90):
      print("\nAccuration more than 90%, training done!")
      self.model.stop_training = True

callbacks = myCallback()

history = model.fit(train_generator, 
                    epochs = 100, 
                    steps_per_epoch = 32,
                    validation_data = validation_generator, 
                    validation_steps = 8,
                    verbose = 1,
                    callbacks = [callbacks])

import numpy as np
import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc = 'upper left')
plt.show()

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model Loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc = 'upper left')
plt.show()

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

with tf.io.gfile.GFile('model.tflite', 'wb') as f:
  f.write(tflite_model)

!ls -la | grep 'model'